version: '2'
services:
  covoijhipster-app:
    image: covoijhipster
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://covoijhipster-mysql:3306/covoijhipster?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://covoijhipster-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://covoijhipster-elasticsearch:9200
    ports:
      - 8080:8080
  covoijhipster-mysql:
    extends:
      file: mysql.yml
      service: covoijhipster-mysql
  covoijhipster-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: covoijhipster-elasticsearch
